name: Test outputs between jobs

on:
  workflow_dispatch:

jobs:

  first_job:
    runs-on: ubuntu-latest
    outputs:
      myOutput1: ${{ steps.first_step_id.outputs.out1 }}
    steps:
      - id: first_step_id
        name: first_step_name
        run: echo "::set-output name=out1::abc"
      - id: second_step_id
        name: second_step_name
        run: echo "::set-output name=out2::def"
      - id: fifth_step_id
        name: fifth_step_name
        run: echo "here is my 5th value $GITHUB_OUTPUT"

  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    outputs:
      myOutput2: ${{ steps.third_step_id.outputs.out3 }}
    steps:
      - id: third_step_id
        name: third_step_name
        run: echo "::set-output name=out3::${{ needs.first_job.outputs.myOutput1 }}"
      - id: fourth_step_id
        name: fourth_step_name
        run: |
          echo "my final value is ${{ steps.third_step_id.outputs.out3 }}"
          echo "out4=myOut" >> $GITHUB_OUTPUT
      - id: sixth_step_id
        name: sixth_step_name
        run: |
          echo "my second final value is ${{ steps.fourth_step_id.outputs.out4 }} and here is the content of the github_output file :"
          echo $GITHUB_OUTPUT
          echo "fin du fichier"
